version: "3.8"

services:
  traefik:
    ports:
     - "80:80"
     # - "8889:8080"
     - "443:443"
  landing_page:
    build:
      context: ./landing_page
  prodigy:
    build:
      context: ./prodigy
